spring:
  application:
    name: shop-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  tomcat:
    basedir: .


mybatis:
  mapper-locations: classpath:mapping/shop/*.xml,classpath:mapping/shop/ex/*.xml
  type-aliases-package: com.geektime.springbootdemo.entity
  configuration:
    map-underscore-to-camel-case: true
#  type-handlers-package:
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  support-methods-arguments: 'true'


